# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: truemark/ssh-agent-action@v1 # Update dengan action yang benar
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to Server
#         run: |
#           ssh -o StrictHostKeyChecking=no ubuntu@34.128.85.227 "
#           cd /var/www/sipasti-staging &&
#           git pull origin main &&
#           npm install --production &&
#           npm run build &&
#           pm2 restart sipasti || pm2 start npm --name sipasti -- start
#           "
